import { cookies } from 'next/headers';
import { AccessToken, RoomServiceClient } from 'livekit-server-sdk';
export class AppError extends Error {constructor(message:string,public status=400){super(message)}}
export function configReady(){return !!(process.env.SUPABASE_URL&&process.env.SUPABASE_ANON_KEY&&process.env.SUPABASE_SERVICE_ROLE_KEY)}
function base(){if(!configReady())throw new AppError('Sign-in and storage are not connected yet. Follow START-HERE.html in the deployment package.',503);return process.env.SUPABASE_URL!.replace(/\/$/,'')}
export async function supabase(path:string,method='GET',body?:unknown,extra:Record<string,string>={}){const r=await fetch(base()+path,{method,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY!,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY!,'Content-Type':'application/json',...extra},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});if(!r.ok){console.error('Supabase request failed',method,path.split('?')[0],r.status);throw new AppError('Storage request failed. Check the Supabase setup and try again.',502)}const txt=await r.text();return txt?JSON.parse(txt):null}
export async function authCall(path:string,body?:unknown,access?:string){const r=await fetch(base()+'/auth/v1/'+path,{method:body===undefined?'GET':'POST',headers:{apikey:process.env.SUPABASE_ANON_KEY!,'Content-Type':'application/json',...(access?{Authorization:'Bearer '+access}:{})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw new AppError(r.status===429?'Too many attempts. Please wait before trying again.':path==='user'?'Please sign in to continue.':String(data.msg||data.message||data.error_description||'Sign-in failed. Try again.'),path==='user'?401:r.status);return data}
export async function user(){const c=await cookies();const t=c.get('castora_access')?.value;if(!t)throw new AppError('Please sign in to continue.',401);const u=await authCall('user',undefined,t);const email=String(u.email||'').toLowerCase();if(!u.id||!u.email_confirmed_at)throw new AppError('Please verify your email to continue.',401);const canHost=(process.env.CASTORA_HOST_EMAILS||'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean).includes(email);return {userId:u.id,email,displayName:email,canHost};}
export function requireHost(u:{canHost:boolean}){if(!u.canHost)throw new AppError('This account is an attendee. The site owner must add your email to CASTORA_HOST_EMAILS to allow hosting.',403)}
export function configured(){return !!(process.env.LIVEKIT_URL&&process.env.LIVEKIT_API_KEY&&process.env.LIVEKIT_API_SECRET)}
export function service(){if(!configured())throw new AppError('Connect your LiveKit account in Netlify environment settings before going live.',503);return new RoomServiceClient(process.env.LIVEKIT_URL!.replace('wss:','https:'),process.env.LIVEKIT_API_KEY,process.env.LIVEKIT_API_SECRET)}
export async function token(room:string,identity:string,name:string,publish:boolean){const t=new AccessToken(process.env.LIVEKIT_API_KEY,process.env.LIVEKIT_API_SECRET,{identity,name,ttl:'2m'});t.addGrant({room,roomJoin:true,canSubscribe:true,canPublish:publish,canPublishData:true});return t.toJwt()}
export async function rows(table:string,filters:Record<string,string>={}){return supabase('/rest/v1/castora_'+table+'?'+new URLSearchParams(filters))}
export async function insert(table:string,data:unknown){return supabase('/rest/v1/castora_'+table,'POST',data,{Prefer:'return=representation'})}
export async function update(table:string,filters:Record<string,string>,data:unknown){return supabase('/rest/v1/castora_'+table+'?'+new URLSearchParams(filters),'PATCH',data,{Prefer:'return=representation'})}
export async function eventFor(id:string,uid:string,invite:string|null=null){if(!/^[a-f0-9-]{36}$/i.test(id))throw new AppError('Event not found.',404);const [e]=await rows('events',{id:'eq.'+id,limit:'1'});if(!e)throw new AppError('Event not found.',404);if(e.owner!==uid&&e.access==='private'&&e.invite!==invite)throw new AppError('An invitation link is required for this event.',403);return e}
export function failure(e:unknown){return Response.json({error:e instanceof Error?e.message:'Something went wrong. Please try again.'},{status:e instanceof AppError?e.status:400,headers:{'Cache-Control':'private, no-store'}})}
export function sameOrigin(r:Request){const origin=r.headers.get('origin');const requestHost=r.headers.get('host')||new URL(r.url).host;if(r.headers.get('sec-fetch-site')==='cross-site'||(origin&&new URL(origin).host!==requestHost))throw new AppError('Request origin not allowed.',403)}
export function json(data:unknown){return Response.json(data,{headers:{'Cache-Control':'private, no-store'}})}
